# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e62d637f84c55d19ace647278d877a752d407e0176ca251b000911a4f46cffdcbd87959ca91146bfe9e2e031dcf9e51c90e9e7d1f0308aec5c7287a550656dee

test:
  secret_key_base: 588ac45f06bd49284e6ed574d7d328b09db9ab3bf7dc6a1794b7a95b78221780ad1cacf400699475107bf6e26692a0c7c1a47174650e7509a7c9752daa13b440

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
